FROM glm4voice-runtime:0.1
RUN rm -rf /root/.config/pip /opt/conda/pip.conf && \
    pip install --no-cache-dir \
    --index-url https://download.pytorch.org/whl/cu128 \
    --extra-index-url https://pypi.org/simple \
    torch==2.9.1+cu128 torchaudio==2.9.1+cu128
