"""Publish a model to a PRIVATE Hugging Face repo: first the untouched base (tag `base`), then the fine-tune.

  python publish_hf.py asr    # -> lewenberg/mms-1b-somali            (base: facebook/mms-1b-all + som adapter)
  python publish_hf.py flow   # -> lewenberg/glm-4-voice-decoder-omar (base: THUDM/glm-4-voice-decoder)

The repo history then reads: base -> fine-tuned, so any result can be compared against the exact starting point.
Re-running is safe: the base commit is only made once; the fine-tune commit is skipped if unchanged.
"""
import argparse
import json
import os
import shutil
import subprocess
import tempfile
from pathlib import Path

from common import DECODER_PATH, REPO, WORK, log

L = log("publish_hf")
NS = os.environ.get("SO_HF_NAMESPACE", "lewenberg")


def git_rev():
    try:
        return subprocess.check_output(["git", "-C", str(REPO), "rev-parse", "--short", "HEAD"], text=True).strip()
    except Exception:
        return "unknown"


def tag(api, repo, name, msg):
    try:
        api.create_tag(repo, tag=name, tag_message=msg)
    except Exception as e:                      # already exists -> fine on re-runs
        L.info("tag %s: %s", name, str(e).splitlines()[0][:120])


def ensure_base(api, repo, stage_fn, msg):
    refs = api.list_repo_refs(repo)
    if any(t.name == "base" for t in refs.tags):
        L.info("%s: base already published", repo)
        return
    with tempfile.TemporaryDirectory() as d:
        stage_fn(Path(d))
        api.upload_folder(repo_id=repo, folder_path=d, commit_message=msg)
    tag(api, repo, "base", msg)


def card(title, body):
    return f"---\ntags: [somali, speech]\n---\n# {title}\n\n{body}\n"


def publish_asr(api, run):
    from huggingface_hub import hf_hub_download
    repo = f"{NS}/mms-1b-somali"
    api.create_repo(repo, private=True, exist_ok=True)

    def base(d):
        for f in ["config.json", "model.safetensors", "preprocessor_config.json", "special_tokens_map.json",
                  "tokenizer_config.json", "vocab.json", "adapter.som.safetensors", "README.md"]:
            shutil.copy(hf_hub_download("facebook/mms-1b-all", f), d / f)
    ensure_base(api, repo, base, "base: facebook/mms-1b-all (unmodified, incl. Somali adapter)")

    final = WORK / "runs" / run / "final"
    evals = {p.stem: json.loads(p.read_text()) for p in (WORK / "eval_asr").glob("*.json")}
    rows = "\n".join(f"| {k} | {v.get('test', {}).get('cer')} | {v.get('test', {}).get('wer')} | "
                     f"{v.get('val', {}).get('cer')} | {v.get('val', {}).get('wer')} |" for k, v in sorted(evals.items()))
    with tempfile.TemporaryDirectory() as d:
        d = Path(d)
        for f in final.iterdir():
            if f.is_file() and f.name != "training_args.bin":
                shutil.copy(f, d / f.name)
        (d / "eval").mkdir()
        for p in (WORK / "eval_asr").glob("*.json"):
            shutil.copy(p, d / "eval" / p.name)
        (d / "README.md").write_text(card("MMS-1b-all, fine-tuned for Somali ASR", f"""
Base: `facebook/mms-1b-all` with its Somali (`som`) adapter (see tag `base`). Fine-tuned with CTC on ~57 h of
Somali TV/podcast speech (5 channels; transcripts machine-generated by `microsoft/mai-transcribe-2`, cleaned).
Held-out splits are whole episodes. Text is lowercase, letters/digits/'/-, no punctuation.

| model | test CER | test WER | val CER | val WER |
|---|---|---|---|---|
{rows}

```python
from transformers import AutoProcessor, Wav2Vec2ForCTC
proc = AutoProcessor.from_pretrained("{repo}", target_lang="som")
model = Wav2Vec2ForCTC.from_pretrained("{repo}", target_lang="som")
```

Reproduce: https://github.com/alimaslax/glm4-voice-so (commit `{git_rev()}`), `finetune/run.sh prepare_asr`,
`train_asr`, `eval_asr`. License follows the base model (CC-BY-NC 4.0).
"""))
        api.upload_folder(repo_id=repo, folder_path=str(d), commit_message=f"fine-tune {run} (code {git_rev()})")
    tag(api, repo, run, f"fine-tune {run}")
    L.info("published https://huggingface.co/%s", repo)


def publish_flow(api, run):
    repo = f"{NS}/glm-4-voice-decoder-omar"
    api.create_repo(repo, private=True, exist_ok=True)

    def base(d):
        for f in DECODER_PATH.iterdir():
            if f.is_file():
                shutil.copy(f, d / f.name)
    ensure_base(api, repo, base, "base: THUDM/glm-4-voice-decoder (unmodified)")

    run_dir = WORK / "runs" / run
    latest = (run_dir / "latest").resolve()
    report = WORK / "resynth" / run
    with tempfile.TemporaryDirectory() as d:
        d = Path(d)
        shutil.copy(latest / "flow.pt", d / "flow.pt")          # config.yaml + hift.pt unchanged from base
        if (latest / "samples").exists():
            shutil.copytree(latest / "samples", d / "samples")
        for name in ("report.json", "README.md"):
            if (report / name).exists():
                (d / "eval").mkdir(exist_ok=True)
                shutil.copy(report / name, d / "eval" / name)
        (d / "README.md").write_text(card("GLM-4-Voice decoder, fine-tuned to Omar's voice", f"""
Base: `THUDM/glm-4-voice-decoder` (tag `base`). Only `flow.pt` (tokens -> mel) is fine-tuned, on Omar's
single-speaker Somali podcast clips (ECAPA speaker-verified). `hift.pt` and `config.yaml` are unchanged.
Drop-in: point GLM-4-Voice's `--flow-path` at a download of this repo. Checkpoint: `{latest.name}`.
Samples: `samples/` (rendered from held-out clips' speech tokens). Resynthesis eval: `eval/`.

Reproduce: https://github.com/alimaslax/glm4-voice-so (commit `{git_rev()}`), `finetune/run.sh train_flow`.
"""))
        api.upload_folder(repo_id=repo, folder_path=str(d), commit_message=f"fine-tune {run} {latest.name} (code {git_rev()})")
    tag(api, repo, f"{run}-{latest.name}", f"fine-tune {run}")
    L.info("published https://huggingface.co/%s", repo)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("what", choices=["asr", "flow"])
    p.add_argument("--run", default=None)
    a = p.parse_args()
    from huggingface_hub import HfApi
    api = HfApi(token=os.environ["HF_TOKEN"])
    if a.what == "asr":
        publish_asr(api, a.run or "asr_mms")
    else:
        publish_flow(api, a.run or "flow_omar")


if __name__ == "__main__":
    main()
